# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alexander Järnehalls DPY
email: alexander@jarnehall.se
description: En sida för min utbildning till front-end-utvecklare
baseurl: ""
url: "http://jarnehall.se" # the base hostname & protocol for your site
timezone: Europe/Stockholm

# Build settings
markdown: kramdown
permalink: /:title/

# Filtering Content
show_drafts: false

# Post settings
excerpt_separator: <!--more-->

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Alexander Järnehall"
